language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
env:
  - JWT_SECRET=AEkli94tscZlg4a0oORnYzR76PuczYTB
services:
  - mongodb
before_script:
  - sleep 15
script:
  - npx prettier --check "src/**/*.ts"
  - npx jest -i
